version: '3.7'

volumes:
  data:

services:
  app:
    build:
      context: .
    volumes:
      - ./data:/root/data
    ports:
      - '5050:5050'
    user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
